# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  
  
  #########################################################
  # Parte de CTE e MDFe Comentado para deploy mais rápido #
  # #######################################################


  - task: NuGetToolInstaller@1

  - task: DotNetCoreCLI@2
    displayName: "Build DFe Classes"
    inputs:
      command: 'build'
      projects: './DFe.Classes/DFe.Classes.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build DFe Utils"
    inputs:
      command: 'build'
      projects: './DFe.Classes/DFe.Classes.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build DFe Wsdl"
    inputs:
      command: 'build'
      projects: './DFe.Wsdl/DFe.Wsdl.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Classes"
    inputs:
      command: 'build'
      projects: './NFe.Classes/NFe.Classes.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Servicos"
    inputs:
      command: 'build'
      projects: './NFe.Servicos/NFe.Servicos.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Utils"
    inputs:
      command: 'build'
      projects: './NFe.Utils/NFe.Utils.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Wsdl Standard"
    inputs:
      command: 'build'
      projects: './NFe.Wsdl.Standard/NFe.Wsdl.Standard.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Danfe Base"
    inputs:
      command: 'build'
      projects: './NFe.Danfe.Base/NFe.Danfe.Base.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Danfe Open Fast"
    inputs:
      command: 'build'
      projects: './NFe.Danfe.OpenFast/NFe.Danfe.OpenFast.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Danfe Fast Skia"
    inputs:
      command: 'build'
      projects: './NFe.Danfe.Fast.Skia/NFe.Danfe.Fast.Skia.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: "Build Nfe Danfe Fast"
    inputs:
      command: 'build'
      projects: './NFe.Danfe.Fast/NFe.Danfe.Fast.csproj'
      arguments: '-c "Release"'
      workingDirectory: '$(Build.SourcesDirectory)'

#  - task: DotNetCoreCLI@2
#    displayName: "Build Mdfe Classes"
#    inputs:
#      command: 'build'
#      projects: './MDFe.Classes/MDFe.Classes.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Mdfe Utils"
#    inputs:
#      command: 'build'
#      projects: './MDFe.Utils/MDFe.Utils.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Mdfe Wsdl"
#    inputs:
#      command: 'build'
#      projects: './MDFe.Wsdl/MDFe.Wsdl.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Mdfe Servicos"
#    inputs:
#      command: 'build'
#      projects: './MDFe.Servicos/MDFe.Servicos.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Damdfe OpenFast"
#    inputs:
#      command: 'build'
#      projects: './MDFe.Damdfe.OpenFast/MDFe.Damdfe.OpenFast.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Classes"
#    inputs:
#      command: 'build'
#      projects: './CTe.Classes/CTe.Classes.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Utils"
#    inputs:
#      command: 'build'
#      projects: './CTe.Utils/CTe.Utils.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Wsdl"
#    inputs:
#      command: 'build'
#      projects: './CTe.Wsdl/CTe.Wsdl.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Servicos"
#    inputs:
#      command: 'build'
#      projects: './CTe.Servicos/CTe.Servicos.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Dacte Base"
#    inputs:
#      command: 'build'
#      projects: './CTe.Dacte.Base/CTe.Dacte.Base.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Dacte OpenFast"
#    inputs:
#      command: 'build'
#      projects: './CTe.Dacte.OpenFast/CTe.Dacte.OpenFast.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'
#
#  - task: DotNetCoreCLI@2
#    displayName: "Build Cte Dacte Fast"
#    inputs:
#      command: 'build'
#      projects: './CTe.Dacte.Fast/CTe.Dacte.Fast.csproj'
#      arguments: '-c "Release"'
#      workingDirectory: '$(Build.SourcesDirectory)'

  - task: NuGetCommand@2
    displayName: Gera Pacote Hercules.OpenLine.Net.NFe.NFCe
    inputs:
      command: 'pack'
      packagesToPack: '$(Build.SourcesDirectory)/NuGet/Hercules.NET.NFe.NFCe/Hercules.OpenLine.NET.NFe.NFCe.nuspec'
      packDestination: '$(Build.ArtifactStagingDirectory)/Hercules.OpenLine.NET.NFe.NFCe.nupkg'
      versioningScheme: 'off'

  - task: PublishBuildArtifacts@1
    displayName: Publica Aterfato Hercules.OpenLine.Net.NFe.NFCe
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Hercules.OpenLine.NET.NFe.NFCe.nupkg'
      ArtifactName: 'hercules.dfe'
      publishLocation: 'Container'

#  - task: NuGetCommand@2
#    displayName: Gera Pacote Hercules.OpenLine.NET.CTe
#    inputs:
#      command: 'pack'
#      packagesToPack: '$(Build.SourcesDirectory)/NuGet/Hercules.NET.CTe/Hercules.OpenLine.NET.CTe.nuspec'
#      packDestination: '$(Build.ArtifactStagingDirectory)/Hercules.OpenLine.NET.CTe.nupkg'
#      versioningScheme: 'off'
#  
#  - task: PublishBuildArtifacts@1
#    displayName: Publica Aterfato Hercules.OpenLine.NET.CTe
#    inputs:
#      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Hercules.OpenLine.NET.CTe.nupkg'
#      ArtifactName: 'hercules.cte'
#      publishLocation: 'Container'
